substitutions:
  name: bt-vevor-ble
  friendly_name: Diesel Air Heater

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  platform: esphome
  password: !secret ota_password

# Web Server
web_server:
  port: 80

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "VevorBLE Hotspot"
    password: "password123"

# Essential: Define scan parameters or the client won't find the device
esp32_ble_tracker:
  scan_parameters:
    interval: 300ms
    window: 200ms
    active: true

globals:
  - id: heater_passkey
    type: int
    initial_value: !secret passkey

# 1. Connection Tracking
binary_sensor:
  - platform: template
    id: heater_ble_connected
    name: "Heater BLE Connected"
    internal: true 

  - platform: template
    id: heater_status
    name: "Heater Running"
    device_class: power

# 2. BLE Client
ble_client:
  - mac_address: !secret mac_address
    id: heater_ble
    on_connect:
      - logger.log: "BLE connected to heater"
      - binary_sensor.template.publish:
          id: heater_ble_connected
          state: ON
    on_disconnect:
      - logger.log: "BLE disconnected"
      - binary_sensor.template.publish:
          id: heater_ble_connected
          state: OFF

# 3. Interval Polling
interval:
  - interval: 5s
    id: heater_poll
    then:
      - if:
          condition:
            binary_sensor.is_on: heater_ble_connected
          then:
            - logger.log: "Polling heater for telemetry..."
            - ble_client.ble_write:
                id: heater_ble
                service_uuid: "0000ffe0-0000-1000-8000-00805f9b34fb"
                characteristic_uuid: "0000ffe1-0000-1000-8000-00805f9b34fb"
                value: !lambda |-
                  int pk = id(heater_passkey);
                  uint8_t pass_hi = pk / 100;
                  uint8_t pass_lo = pk % 100;
                  uint8_t cmd = 0x01;
                  uint8_t checksum = (pass_hi + pass_lo + cmd) & 0xFF;
                  return {0xAA, 0x55, pass_hi, pass_lo, cmd, 0x00, 0x00, checksum};

text_sensor:
  - platform: template
    id: glow_plug_status
    name: "Glow Plug Status"
    icon: "mdi:fire"

  - platform: template
    id: heater_mode_text
    name: "Heater Mode"
    icon: "mdi:thermometer"

  - platform: template
    id: temp_unit
    name: "Temperature Unit"
    icon: "mdi:thermometer"
    
  - platform: template
    id: last_packet_hex
    name: "Last Hex Packet"
    icon: "mdi:code-string"

  - platform: version
    hide_timestamp: true
    name: 'ESPHome Version'

  - platform: wifi_info
    ip_address:
      name: 'IP Address'
      icon: mdi:wifi
    ssid:
      name: 'Connected SSID'
      icon: mdi:wifi-strength-2

# Sensors
sensor:
  - platform: uptime
    name: "ESP Uptime"
    id: uptime_sensor

  - platform: template
    id: error_code
    name: "Error Code"
    accuracy_decimals: 0
    icon: "mdi:alert-circle-outline"

  - platform: template
    id: battery_voltage
    name: "Battery Voltage"
    unit_of_measurement: "V"
    device_class: voltage
    accuracy_decimals: 1
    icon: "mdi:car-battery"

  - platform: template
    id: altitude
    name: "Altitude"
    unit_of_measurement: "m"
    device_class: distance
    accuracy_decimals: 0
    icon: "mdi:summit"

  - platform: template
    id: room_temperature
    name: "Cabin Temperature"
    unit_of_measurement: "째C"
    device_class: temperature
    accuracy_decimals: 1
    icon: "mdi:home-thermometer"

  - platform: template
    id: heating_temperature
    name: "Heater Core Temperature"
    unit_of_measurement: "째C"
    device_class: temperature
    accuracy_decimals: 1
    icon: "mdi:radiator"
  
  - platform: template
    id: target_temp_sensor
    name: "Target Temperature"
    unit_of_measurement: "째C"
  
  - platform: template
    id: target_level_sensor
    name: "Target Level"
    unit_of_measurement: "Level"
  
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 120s

  # MAIN DECODER LOGIC
  - platform: ble_client
    type: characteristic
    id: ble_master_receiver
    ble_client_id: heater_ble
    service_uuid: "0000ffe0-0000-1000-8000-00805f9b34fb"
    characteristic_uuid: "0000ffe1-0000-1000-8000-00805f9b34fb"
    notify: true
    name: "Heater Raw Mode"
    accuracy_decimals: 0
    lambda: |-
      std::string hex_str = format_hex_pretty(x);
      ESP_LOGD("HEATER", "Rx: %s", hex_str.c_str());
      id(last_packet_hex).publish_state(hex_str);

      // Check for valid header (AA 66) AND ACCEPT 20 BYTES
      if (x.size() >= 20 && x[0] == 0xAA && x[1] == 0x66) {
        
        uint8_t onOff = x[3];
        uint8_t errcode = x[4];
        uint8_t runStep = x[5];
        uint8_t runMode = x[8]; // 01 = Level, 02 = Auto
        
        // Little Endian Math (Low Byte + High Byte * 256)
        float voltage = (float)(x[11] + (x[12] * 256)) / 10.0f;
        float shellTemp = (float)((int16_t)(x[13] + (x[14] * 256)));
        float roomTemp = (float)((int16_t)(x[15] + (x[16] * 256))); 
        float altitude_val = (float)(x[6] + (x[7] * 256));
        float runT = (float)x[9];
        uint8_t runG = x[10];
        
        uint8_t tempUnit = 0;
        if (x.size() > 27) tempUnit = x[27] & 0x0F;

        // --- Update Numeric Sensors ---
        id(battery_voltage).publish_state(voltage);
        id(altitude).publish_state(altitude_val);
        id(room_temperature).publish_state(roomTemp);
        id(heating_temperature).publish_state(shellTemp);
        id(error_code).publish_state(errcode);
        id(heater_status).publish_state(onOff > 0);
        id(heater_level).publish_state(runG);
        id(heater_temperature).publish_state(runT);
        id(target_temp_sensor).publish_state(runT);
        id(target_level_sensor).publish_state(runG);

        // --- Handle Mode Text Explicitly ---
        if (runMode == 0x01) {
            id(heater_mode_text).publish_state("Level");
            ESP_LOGD("HEATER", "Mode: Level");
        } 
        else if (runMode == 0x02) {
            id(heater_mode_text).publish_state("Automatic");
            ESP_LOGD("HEATER", "Mode: Auto");
        } 
        else {
            id(heater_mode_text).publish_state("Standby");
        }

        // --- Handle Units ---
        if (tempUnit == 1) {
            id(temp_unit).publish_state("F");
        } else {
            id(temp_unit).publish_state("C");
        }

        // --- Handle Run State Text ---
        if (runStep == 2 || runStep == 3) {
          id(glow_plug_status).publish_state("Heating");
        } else if (runStep == 4) {
          id(glow_plug_status).publish_state("Running");
        } else if (runStep == 5) {
          id(glow_plug_status).publish_state("Cooling Down");
        } else {
          id(glow_plug_status).publish_state("Idle");
        }

        return (float)runMode;
      }
      return 0.0;

# Switches
switch:
  - platform: template
    id: heater_power
    name: "Heater Power"
    icon: "mdi:radiator"
    optimistic: true
    turn_on_action:
      - ble_client.ble_write:
          id: heater_ble
          service_uuid: "0000ffe0-0000-1000-8000-00805f9b34fb"
          characteristic_uuid: "0000ffe1-0000-1000-8000-00805f9b34fb"
          value: !lambda |-
            int pk = id(heater_passkey);
            uint8_t pass_hi = pk / 100;
            uint8_t pass_lo = pk % 100;
            uint8_t cmd = 0x03;
            uint8_t checksum = (pass_hi + pass_lo + cmd + 0x01) & 0xFF;
            return {0xAA, 0x55, pass_hi, pass_lo, cmd, 0x01, 0x00, checksum};
    turn_off_action:
      - ble_client.ble_write:
          id: heater_ble
          service_uuid: "0000ffe0-0000-1000-8000-00805f9b34fb"
          characteristic_uuid: "0000ffe1-0000-1000-8000-00805f9b34fb"
          value: !lambda |-
            int pk = id(heater_passkey);
            uint8_t pass_hi = pk / 100;
            uint8_t pass_lo = pk % 100;
            uint8_t cmd = 0x03;
            uint8_t checksum = (pass_hi + pass_lo + cmd) & 0xFF;
            return {0xAA, 0x55, pass_hi, pass_lo, cmd, 0x00, 0x00, checksum};
    lambda: |-
      return id(heater_status).state;

# Select for mode
select:
  - platform: template
    id: heater_mode
    name: "Heater Mode"
    options:
      - "Level"
      - "Automatic"
    initial_option: "Level"
    optimistic: true
    set_action:
      then:
        - if:
            condition:
              lambda: 'return x == "Automatic";'
            then:
              - ble_client.ble_write:
                  id: heater_ble
                  service_uuid: "0000ffe0-0000-1000-8000-00805f9b34fb"
                  characteristic_uuid: "0000ffe1-0000-1000-8000-00805f9b34fb"
                  value: !lambda |-
                    int pk = id(heater_passkey);
                    uint8_t pass_hi = pk / 100;
                    uint8_t pass_lo = pk % 100;
                    uint8_t cmd = 0x02;
                    uint8_t checksum = (pass_hi + pass_lo + cmd + 0x02) & 0xFF;
                    return {0xAA, 0x55, pass_hi, pass_lo, cmd, 0x02, 0x00, checksum};
            else:
              - ble_client.ble_write:
                  id: heater_ble
                  service_uuid: "0000ffe0-0000-1000-8000-00805f9b34fb"
                  characteristic_uuid: "0000ffe1-0000-1000-8000-00805f9b34fb"
                  value: !lambda |-
                    int pk = id(heater_passkey);
                    uint8_t pass_hi = pk / 100;
                    uint8_t pass_lo = pk % 100;
                    uint8_t cmd = 0x02;
                    uint8_t checksum = (pass_hi + pass_lo + cmd + 0x01) & 0xFF;
                    return {0xAA, 0x55, pass_hi, pass_lo, cmd, 0x01, 0x00, checksum};

number:
  # Temperature Setpoint (Auto Mode)
  - platform: template
    id: heater_temperature
    name: "Heater Temperature Target"
    unit_of_measurement: "째C"
    icon: "mdi:thermometer"
    min_value: 8
    max_value: 36
    step: 1
    optimistic: true
    set_action:
      then:
        - ble_client.ble_write:
            id: heater_ble
            service_uuid: "0000ffe0-0000-1000-8000-00805f9b34fb"
            characteristic_uuid: "0000ffe1-0000-1000-8000-00805f9b34fb"
            value: !lambda |-
              uint8_t temp = (uint8_t)x;
              int pk = id(heater_passkey);
              uint8_t pass_hi = pk / 100;
              uint8_t pass_lo = pk % 100;
              uint8_t cmd = 0x04;
              uint8_t checksum = (pass_hi + pass_lo + cmd + temp) & 0xFF;
              return {0xAA, 0x55, pass_hi, pass_lo, cmd, temp, 0x00, checksum};

  # Level Setpoint (Level Mode)
  - platform: template
    id: heater_level
    name: "Heater Level Target"
    unit_of_measurement: "Level"
    icon: "mdi:format-list-numbered"
    min_value: 1
    max_value: 10
    step: 1
    optimistic: true
    set_action:
      then:
        - ble_client.ble_write:
            id: heater_ble
            service_uuid: "0000ffe0-0000-1000-8000-00805f9b34fb"
            characteristic_uuid: "0000ffe1-0000-1000-8000-00805f9b34fb"
            value: !lambda |-
              uint8_t level = (uint8_t)x;
              int pk = id(heater_passkey);
              uint8_t pass_hi = pk / 100;
              uint8_t pass_lo = pk % 100;
              uint8_t cmd = 0x04;
              uint8_t checksum = (pass_hi + pass_lo + cmd + level) & 0xFF;
              return {0xAA, 0x55, pass_hi, pass_lo, cmd, level, 0x00, checksum};
